### ISSUE TITLE
Crew assignments getting lost when locomotives moved

### ISSUE THREAD

**Issue by Fevix** [SgtMoloch/MoveTheEquipment#8]
Title. Becomes a hassle when crew assignments are used on multiplayer servers to designate certain trains being part of certain lines.

**Comment by SgtMoloch** [comment]
Never tested this, but it makes sense because I’m technically respawning the engines and cars, as that’s the only way to successfully move them. 

As the new update addresses the core reason of this mod existing, it is now obsolete. 

If there is enough interest I may look into updating it but I don’t see that being likely.
